CREATE TABLE IF NOT EXISTS USUARIO (
  nombre VARCHAR(50) NOT NULL,
  documento INT(20) NOT NULL,
  contrasena VARCHAR(20) NOT NULL,
  tipoUsuario VARCHAR(20) NOT NULL,
  email VARCHAR(150) NOT NULL);
